import Image from 'next/image'

const paymentMethods = [
  {
    title: 'YouTube\'s Monetization Model',
    description: 'YouTube\'s monetization model is based on the number of views and clicks on ads displayed before, during, and after videos.',
    icon: '/images/yt1.png',
    details: [
      'Have at least 1,000 subscribers',
      'Have at least 4,000 watch hours in the past 12 months',
      'Comply with YouTube\'s community guidelines and terms of service'
    ],
    requirements: 'Requirements for Monetization'
  },
  {
    title: 'How YouTube Calculates Earnings',
    description: 'YouTube calculates earnings based on various factors that determine your revenue from advertisements.',
    icon: '/images/yt2.png',
    details: [
      'Cost Per Click (CPC): The amount advertisers pay for each ad click',
      'Cost Per Mille (CPM): The amount advertisers pay for every 1,000 ad views',
      'Ad Impressions: The number of times ads are displayed',
      'Click-Through Rate (CTR): The percentage of viewers who click on ads'
    ]
  },
  {
    title: 'YouTube\'s Payment Structure',
    description: 'YouTube has a clear and transparent payment structure that determines how creators earn from their content.',
    icon: '/images/yt3.png',
    details: [
      '55% of ad revenue: Creators receive 55% of the ad revenue generated by their videos',
      'Per 1,000 views: Creators earn between $0.50 to $5 per 1,000 views, depending on the niche, audience, and ad engagement'
    ]
  },
  {
    title: 'Payment Thresholds',
    description: 'To receive payments, creators must meet specific thresholds and follow payment schedules.',
    icon: '/images/yt4.png',
    details: [
      '$100 for AdSense: Creators must earn at least $100 from AdSense to receive payments',
      '$10 for YouTube Premium: Creators must earn at least $10 from YouTube Premium to receive payments',
      'Monthly: Payments are made on the 21st of each month for the previous month\'s earnings',
      'Via AdSense: Payments are made through AdSense, which can be linked to a bank account or PayPal'
    ],
    note: 'Keep in mind that YouTube\'s payment structure and thresholds may vary depending on the creator\'s location, niche, and audience.'
  }
]

export default function HowYoutubePays() {
  return (
    <section className="py-16 bg-white">
      <div className="container mx-auto px-4">
        <div className="text-center mb-12">
          <h2 className="text-4xl font-bold text-gray-900 mb-4">How YouTube Pays</h2>
          <p className="text-xl text-gray-600">Here's a simplified explanation of how YouTube pays its creators
          </p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {paymentMethods.map((method, index) => (
            <div 
              key={index}
              className="bg-gray-50 rounded-xl p-6 transform transition-all hover:scale-105 hover:shadow-lg"
            >
              <div className="relative h-16 w-16 mx-auto mb-4">
                <Image
                  src={method.icon}
                  alt={method.title}
                  fill
                  className="object-contain"
                />
              </div>
              <div className="text-center">
                <h3 className="text-xl font-semibold text-gray-900 mb-3">{method.title}</h3>
                <p className="text-gray-600 mb-4">{method.description}</p>
                {method.requirements && (
                  <h4 className="text-lg font-medium text-blue-600 mb-3">{method.requirements}</h4>
                )}
                <ul className="text-left space-y-2">
                  {method.details.map((detail, idx) => (
                    <li key={idx} className="flex items-start">
                      <span className="text-blue-500 mr-2">•</span>
                      <span className="text-gray-600">{detail}</span>
                    </li>
                  ))}
                </ul>
                {method.note && (
                  <p className="mt-4 text-sm text-gray-500 italic">{method.note}</p>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
} 